### ISSUE TITLE
FEAT | Base NPC class

### ISSUE THREAD

**Issue by DennisSSDev** [nujas/JanusVagabond#16]
## 🚀 Feature Proposal
All NPC and player will inherit from it, based on a goal driven architecture

**Comment by louisgv** [comment]
Methods:
+ MoveTo(Vector2 location)
+ MoveTo(BaseCharacter other)
+ RunFrom(BaseCharacter other)
+ MoveTo(BaseStructure structure)
+ Attack(BaseCharacter other)

+ OnReceiveDamage(int damage)
+ OnArrived()

**Comment by DennisSSDev** [comment]
Base NPC Data:

- Health
- Movement Speed
- Attack Strength
